README template
ITMO-NSS-team/open-source-ops pull request #12
Opened 2023-02-08 15:33 UTC by pashtetttt

Вариант типового шаблона структуры README для открытых проектов.

2023-02-08 18:19 UTC, 1spb-org commented
README.md - текстовый формат со встраиваемыми картинками, подходит для главной страницы проекта.  
Его структура индивидуальна от проекта к проекту, большого смысла стандартизировать её не имеет. 
А для индексации по метаданным лучше что-нибудь [такое](https://github.com/iieehs/index/blob/main/NOTES.md).
IMHO.

2023-02-08 18:23 UTC, nicl-nno commented
>Его структура индивидуальна от проекта к проекту, большого смысла стандартизировать её не имеет.

Всё-таки для проектов в области ИИ можно выделить достаточно часто встречающиеся общие части.

Для уже состоявшихся проектов всё может быть индивидуально, но цель - дать начинающим разработчикам ориентир, который поможет им получить как-то достойный начальный вариант.

Про метаданные не совсем понял.

2023-02-08 18:46 UTC, 1spb-org commented
> README.md - текстовый формат со встраиваемыми картинками, подходит для главной страницы проекта.
> Его структура индивидуальна от проекта к проекту, большого смысла стандартизировать её не имеет.

Речь о том, что коль скоро структура README стандартна, то её лучше держать в метаданных, которые легко парсить.
По ним README.md можно будет, кстати, генерировать автоматически.

2023-02-08 19:34 UTC, nicl-nno commented
>Речь о том, что коль скоро структура README стандартна, то её лучше держать в метаданных, которые легко парсить.

Это может быть полезно для ряда задач, но всё-таки README для новичков хочется иметь максимально простым.
Пример с авто-генерацией можно в будущем сделать отдельно как advanced.

2023-02-08 20:11 UTC, nicl-nno commented on template_README.rst
> +Name of the project or a logo
Мне кажется, что стоит добавить несколько вариантов организации красивых плашек. Все любят плашки.

Так:
![image](https://user-images.githubusercontent.com/5711814/217640455-43ce50df-4097-4d4c-8509-56950bfb64c4.png)
или так:

![image](https://user-images.githubusercontent.com/5711814/217640586-6eb782b1-c6ce-4555-8a85-e4852658e4a2.png)

2023-02-08 20:13 UTC, nicl-nno commented on template_README.rst
> +Describe applications of your project
Тут имеется в виду что-то вроде Examples? Если да - то я бы (1) так и назвал (2) конкретизировал, что и как в этих примерах можно показать.

2023-02-08 20:14 UTC, nicl-nno commented on template_README.rst
> +=================
Тут точно нужно описать, как именно лучше эту структуру показывать. Со многих станется какую-то громозкую ГОСТ-овскую схему вставить.

2023-02-08 20:48 UTC, DRMPN commented
На мой взгляд, самое необходимое, на что нужно уделить особое внимание:

- Как работает проект (прикрепить результаты в виде картинки/гифки)
- Как установить и настроить, желательно расписать все по шагам и самим по инструкции попробовать это сделать
- Пример как запустить и использовать хотя бы одну функцию (начать с импортов)
- Как дополнить этот проект (составить инструкцию или ссылку на готовую, указать требование о детальном описании проделанных/предложенных изменениях)
- В качестве ориентира можно предложить штук 5 хороших примеров readme и штук 5 плохих примеров, как делать не нужно т.к. это лицо проекта

Просто говорю свое мнение, могу быть в чем-то неправым :)

2023-02-17 15:55 UTC, andreygetmanov requested changes

2023-02-17 15:55 UTC, andreygetmanov commented on template_README.rst
> +Project Structure
Мне кажется, стоит делать подразделы одинаковыми стилями заголовков, так что здесь и далее:
`Project Structure`
`------------`

2023-02-17 15:55 UTC, andreygetmanov commented on template_README.rst
> +========
Как правило, репозитории создаются как результат определённого ресёрча, поэтому, имхо, стоит вставить раздел Citation с ссылками на публикации в шаблон (как [здесь](https://github.com/aimclub/FEDOT#citation))

2023-02-17 15:55 UTC, andreygetmanov commented on template_README.rst
> +Describe applications of your project
Согласен с предложением выше. Ещё можно поставить этот раздел после Installation для более последовательного чтения

2023-02-17 15:55 UTC, andreygetmanov commented on template_README.rst
> +Acknowledgments
Я бы ещё добавил раздел Documenation, чтобы промотивировать разработчиков создавать автособираемую документацию

2023-02-17 15:55 UTC, andreygetmanov commented on template_README.rst
> +
Ещё, имхо, не хватает раздела Contribuiton, чтобы каждый желающий поучаствовать в проекте понимал, как это сделать

2023-02-17 16:09 UTC, andreygetmanov commented
Примеры хороших readme (помимо ИТМОшных):
1. https://github.com/pandas-dev/pandas
2. https://github.com/laravel/laravel
3. https://github.com/pytorch/pytorch
4. https://github.com/scikit-learn/scikit-learn

Вот [здесь](https://techrocks.ru/2019/04/16/good-readme-on-github/) (ру) и [здесь](https://github.com/hackergrrl/art-of-readme) (en) есть дельные мысли по поводу написания ридми

2023-02-17 16:20 UTC, andreygetmanov commented
В процессе ревью чужих репо у меня возникла такая мысль:
А что если описывать проект дважды: на языке того, кто понимает, куда он зашёл, и на языке человека, имеющего общие знания в МЛ, но не имеющего конкретные знания в специализации проекта
Когда ревьювил GNN-проекты, мне оч не хватало хотя бы brief обзора простыми словами, как это работает и зачем это нужно

Если предполагается, что репозиториями будут пользоваться не только люди, которые знают что делают, но и те, кому просто интересно что-то новое, имхо, стоит это учитывать

2023-02-17 20:43 UTC, nicl-nno commented
>Ещё, как мне кажется, стоит добавить раздел License, чтобы разработчики не забывали выбирать и указывать тип открытой лицензии

Упомянуть можно, но не обязательно отдельным разделом - в целом-то отображение лицензии гитхаб на себя берет.

>А что если описывать проект дважды

Это сложно формализовать в виде конкретной структуры, но такой совет безусловно дать стоит.

2023-02-17 20:43 UTC, nicl-nno commented on template_README.rst
> +
Это можно и отдельным Contribution.md, чтобы не раздувать объем README.

2023-02-20 08:16 UTC, pashtetttt commented
Исправил. Постарался учесть большинство комментариев.

2023-02-20 15:27 UTC, andreygetmanov commented on template_README.rst
> +Describe applications of your project
[Здесь](https://github.com/hackergrrl/art-of-readme) в разделе `Key Elements` предлагается удобная структура readme для nodejs-модулей. Там же даётся обоснование, почему не стоит ставить разделы `Документация` и `Установка` перед `Примерами`
Статья написана разработчицей nodejs, не все советы и идеи нужно заимствовать, но предлагаемая там последовательность теперь кажется мне более логичной и удобной
Что вы думаете на этот счёт?

2023-02-20 15:31 UTC, andreygetmanov requested changes

2023-02-20 15:31 UTC, andreygetmanov commented on template_README.rst
> +The purpose of the project
Предлагаю добавить раздел `Table of contents` для более удобной навигации ([пример](https://github.com/richardlitt/standard-readme))

2023-02-20 15:39 UTC, andreygetmanov commented
Вот ещё примеры хорошо написанных readme:
1. https://github.com/BrainJS/brain.js 
2. https://github.com/fibo/algebra

В первом мне понравился раздел Examples: достаточно подробно и понятно всё написано. Во втором раздел Quick Start, как мне кажется, оч хорошая идея. Не знаю, в каких случаях его добавлять не нужно, но в большинстве случаев, думаю, стоит

2023-02-21 13:58 UTC, andreygetmanov commented on template_README.rst
> +The purpose of the project
>  Поэтому может быть оставить об этом пометку использования?

Да, согласен

2023-02-21 17:21 UTC, nicl-nno commented on template_README.rst
> +.. image:: /source
Чтобы лучше смотрелось - лучше дать какую-то картинку-заглушку. А то просто битая ссылка: 

![image](https://user-images.githubusercontent.com/5711814/220415542-718407a4-5913-4e95-9893-f7197a3fc55c.png)

2023-02-21 17:21 UTC, nicl-nno commented on template_README.rst
> +.. end-badges
Можно в комментариях или отдельном дать инструкции, как генерировать эти бейджи.

2023-02-21 17:24 UTC, nicl-nno commented on template_README.rst
> +3. https://github.com/aimclub/FEDOT
Если выше испольуются круглые маркеры - тот и тут лучше их.

2023-02-21 17:24 UTC, nicl-nno commented on template_README.rst
> +  doi = {}}
Можно уточнить, что bibtex-ссылку удобно брать с google scholar.

2023-02-27 12:06 UTC, aPovidlo commented on template_README.rst
> +   * - package
@pashtetttt Не совсем уверен, они такой вид и должны иметь или в master появятся значки? И еще вопрос, что если в своем проекте сделал подобное, но они даже не отображаются при рендере? Это нужны какие-то манипуляции с настройками репы?

![image](https://user-images.githubusercontent.com/22475542/221558839-ee451df2-f070-43c7-b6e8-54abba481f87.png)

2023-02-27 15:27 UTC, aPovidlo commented on template_README.rst
> +   * - package
Самостоятельно разобрался в проблеме. Думаю, что может быть стоит добавить в структуру или отдельно куда-нибудь пояснение для того, как сделать оформление |ссылок| и создавать значки через img.shields.io

2023-03-03 20:53 UTC, nicl-nno commented
Не забудь кстати в заглавное README добавить ссылку.

2023-03-06 12:38 UTC, pashtetttt commented on template_README.rst
> +The purpose of the project
Мне идея с Table of contents показалась интересной, поэтому я все-таки ее добавил

2023-03-06 12:39 UTC, pashtetttt commented on template_README.rst
> +.. image:: /source
Добавил логотип университета ИТМО

2023-03-06 12:43 UTC, pashtetttt commented on template_README.rst
> +.. end-badges
Я исправил предыдущий вариант бейджев. Новый вариант, на мой взгляд, интуитивно понятен.. Проверьте, может, он все-таки вызывает вопросы

2023-03-06 12:43 UTC, pashtetttt commented on template_README.rst
> +3. https://github.com/aimclub/FEDOT
Исправил

2023-03-06 12:44 UTC, pashtetttt commented on template_README.rst
> +  doi = {}}
Уточнил

2023-03-13 12:32 UTC, pashtetttt commented
> Примеры хороших readme (помимо ИТМОшных):
> 
> 1. https://github.com/pandas-dev/pandas
> 2. https://github.com/laravel/laravel
> 3. https://github.com/pytorch/pytorch
> 4. https://github.com/scikit-learn/scikit-learn
> 
> Вот [здесь](https://techrocks.ru/2019/04/16/good-readme-on-github/) (ру) и [здесь](https://github.com/hackergrrl/art-of-readme) (en) есть дельные мысли по поводу написания ридми

Из репозиториев-примеров я взял PyTorch, Scikit-learn и FEDOT

2023-03-13 23:10 UTC, pashtetttt commented
> Не забудь кстати в заглавное README добавить ссылку.

Добавил в "Шаблоны" в своей ветке.

2023-03-14 09:34 UTC, nicl-nno commented on README.md
> +- [Типовый шаблон README для open-source проектов](template_README.rst);
Тут д.б. точка, а не ;.

2023-03-14 09:35 UTC, nicl-nno commented on README.md
> +- [Типовый шаблон README для open-source проектов](template_README.rst);
Ну и сам README_template.rst переложи в каталог templates

2023-03-14 12:43 UTC, pashtetttt commented on template_README.rst
> +Describe applications of your project
Переписал. Поставил так: Installation -> Examples -> Project Structure -> Documentation, так как зачастую раздел Установки не занимает много пространства на странице, и читатель может быстро перейти к примерам.

2023-03-14 12:49 UTC, pashtetttt commented
> На мой взгляд, самое необходимое, на что нужно уделить особое внимание:
> 
> * Как работает проект (прикрепить результаты в виде картинки/гифки)
Как работает проект можно прочитать в "The purpose of the project" и в "Examples"
> * Как установить и настроить, желательно расписать все по шагам и самим по инструкции попробовать это сделать
Поле "Installation"
> * Пример как запустить и использовать хотя бы одну функцию (начать с импортов)
Поле "Examples" и "Getting started"
> * Как дополнить этот проект (составить инструкцию или ссылку на готовую, указать требование о детальном описании проделанных/предложенных изменениях)
В этом шаблоне я этого не стал делать, подумал, что это к каждому проекту идет индивидуально, но есть раздел "Contacts", т.е. можно связаться с создателями проекта и предложить изменения.
> * В качестве ориентира можно предложить штук 5 хороших примеров readme и штук 5 плохих примеров, как делать не нужно т.к. это лицо проекта
Сделал раздел примеров хороших README в конце шаблона.
> 
> Просто говорю свое мнение, могу быть в чем-то неправым :)

2023-03-14 13:18 UTC, pashtetttt commented on README.md
> +- [Типовый шаблон README для open-source проектов](template_README.rst);
Исправил.

2023-03-14 13:18 UTC, pashtetttt commented on README.md
> +- [Типовый шаблон README для open-source проектов](template_README.rst);
Переместил.

2023-03-14 13:34 UTC, nicl-nno approved these changes

2023-03-14 13:56 UTC, andreygetmanov approved these changes

2023-03-14 16:35 UTC, andreygetmanov requested changes

2023-03-14 16:35 UTC, andreygetmanov commented on templates/template_README.rst
> +.. _DOI: https://zenodo.org/badge/latestdoi/21369/scikit-learn/scikit-learn
Можно добавить плашку-зеркало гитлаба и заодно закрыть этот [issue](https://github.com/ITMO-NSS-team/open-source-ops/issues/35)
Вот код плашки:

|GitLab|_

.. |GitLab| image:: https://camo.githubusercontent.com/9bd7b8c5b418f1364e72110a83629772729b29e8f3393b6c86bff237a6b784f6/68747470733a2f2f62616467656e2e6e65742f62616467652f6769746c61622f6d6972726f722f6f72616e67653f69636f6e3d6769746c6162
.. _GitLab: https://gitlab.com/gitlab-org/gitlab

2023-03-15 18:55 UTC, nicl-nno commented on templates/template_README.rst
> +.. _DOI: https://zenodo.org/badge/latestdoi/21369/scikit-learn/scikit-learn
Уже влил сам.

2023-03-15 18:56 UTC, andreygetmanov approved these changes

2023-03-16 11:04 UTC, merged