Новая структура репозитория + страницы про научные публикации
ITMO-NSS-team/open-source-ops pull request #19
Opened 2023-02-19 15:48 UTC by nicl-nno

- Сформировал структуру в соотвествие с планами из измеющихся issue
- Добавил короткие описания разделов
- Сделал файл с знакомыми мне журналами, где публикуют статьи про открытый код.

2023-02-19 16:09 UTC, ChrisLisbon approved these changes

2023-02-20 16:04 UTC, andreygetmanov requested changes

2023-02-20 16:04 UTC, andreygetmanov commented on meetups/scios-meetup-1/README.md
> +На мероприятии собрались аспиранты, научные сотрудники и магистринты петербургских вузов, а также представители IT-компаний. Слушатели из других городов присоединились к онлан-трансляции.
*магистранты, *онлайн

2023-02-20 16:04 UTC, andreygetmanov commented on meetups/scios-meetup-1/README.md
> +Своим опытом работы открытым репозиторием поделился [Александр Хватов](https://github.com/SuperSashka), руководитель лаборатории композитного ИИ (ЛабКИИ).
*опытом работы _над_ открытым репозиторием?

2023-02-20 16:04 UTC, andreygetmanov commented on meetups/scios-meetup-1/README.md
> +[Николай Никитин](https://github.com/nicl-nno) рассказал о том, зачем, в целом, делать научный код открытым и каких принципов стоит придерживаться, работая в этом направлении.
*о том, зачем в целом делать... (запятые [лишние](http://new.gramota.ru/spravka/buro/search-answer?s=%D0%B2+%D1%86%D0%B5%D0%BB%D0%BE%D0%BC%5C_))

2023-02-20 20:16 UTC, nicl-nno commented on meetups/scios-meetup-1/README.md
> +[Николай Никитин](https://github.com/nicl-nno) рассказал о том, зачем, в целом, делать научный код открытым и каких принципов стоит придерживаться, работая в этом направлении.
Поправил.

2023-02-20 20:16 UTC, nicl-nno commented on meetups/scios-meetup-1/README.md
> +Своим опытом работы открытым репозиторием поделился [Александр Хватов](https://github.com/SuperSashka), руководитель лаборатории композитного ИИ (ЛабКИИ).
Поправил.

2023-02-20 20:16 UTC, nicl-nno commented on meetups/scios-meetup-1/README.md
> +На мероприятии собрались аспиранты, научные сотрудники и магистринты петербургских вузов, а также представители IT-компаний. Слушатели из других городов присоединились к онлан-трансляции.
Поправил.

2023-02-20 20:16 UTC, nicl-nno commented on science/journals.md
> +# Где можно опубликовать научную статью личный или коллективный open-source проект?
Поправил.

2023-02-20 20:24 UTC, andreygetmanov approved these changes

2023-02-20 20:25 UTC, merged